services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: maadtime
      POSTGRES_USER: maadtime
      POSTGRES_PASSWORD: maadtime123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.development
      DEBUG: "True"
      POSTGRES_HOST: db
    volumes:
      - ./backend:/app
      - media_data_dev:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    image: node:20-alpine
    working_dir: /app
    command: npm run dev
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data_dev:
  media_data_dev:
